pipeline {
    agent any

    stages {
        stage('Install Flask Dependencies') {
            steps {
                script {
                    dir('be') {
                        sh 'pip install -r requirements.txt'
                    }
                }
            }
        }
        stage('Build and Install React App') {
            steps {
                dir('fe') {
                    sh 'npm install'
                    sh 'npm build'
                }
            }
        }

        stage('Start Flask and React') {
            steps {
                parallel(
                    {
                        script {
                            dir('be') {
                                sh 'flask run'
                            }
                        }
                    },
                    {
                        script {
                            dir('fe') {
                                sh 'npm start'
                            }
                        }
                    }
                )
            }
        }
        stage('Test apps') {
            steps {
                script {
                    sh 'curl -f http://localhost:5000' // For Flask
                    sh 'curl -f http://localhost:3000' // For React
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
