pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/BS-PMC-2024/BS-PMC-2024-Team21.git'
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    sh 'docker-compose build'
                }
            }
        }
        stage('Test Docker Compose Build') {
            steps {
                script {
                    sh 'docker-compose up -d'
                    

                    sh 'curl -f http://localhost:5000' // For Flask
                    sh 'curl -f http://localhost:3000' // For React
                }
            }
        }
    }
    post {
        always {
            script {
                // Bring down the Docker Compose services
                sh 'docker-compose down'
                
                // Clean up the workspace
                cleanWs()
            }
        }
    }
}
